/**
 * This file was auto-generated by openapi-typescript.
 * Tickers paths were manually extended for development — run `npm run generate`
 * (with the backend server running) to regenerate from the live OpenAPI spec.
 * Last updated: 2026-06-11 — added /tickers/{symbol}/prices path + PriceBarPageResponse.
 */

export interface paths {
    "/tickers/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated OHLCV price bars for a ticker */
        get: operations["get_ticker_prices_tickers__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search tickers by symbol or name prefix */
        get: operations["search_tickers_tickers_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickers/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single ticker by symbol */
        get: operations["get_ticker_tickers__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 OK with service metadata.  Used by load balancers and the frontend smoke test.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Single ticker entry returned by search and detail endpoints. */
        TickerSearchResult: {
            symbol: string;
            name: string;
            exchange: string;
            asset_type: string;
            currency: string;
            sector?: string | null;
            industry?: string | null;
            /** ISO 8601 datetime of the most recent price bar, or null if no data yet. */
            data_as_of?: string | null;
        };
        /** A single OHLCV candlestick bar. */
        PriceBarItem: {
            /** ISO 8601 timestamp */
            t: string;
            o: number;
            h: number;
            low: number;
            c: number;
            v: number;
            adj_c?: number | null;
        };
        /** Paginated OHLCV response for a single ticker and timeframe. */
        PriceBarPageResponse: {
            symbol: string;
            timeframe: string;
            data_as_of?: string | null;
            bars: components["schemas"]["PriceBarItem"][];
            next_cursor?: string | null;
        };
        /** Paginated response for the search endpoint. */
        TickerSearchResponse: {
            results: components["schemas"]["TickerSearchResult"][];
            total: number;
        };
        /**
         * HealthResponse
         * @description Shape of the /health response body.
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' when the service is reachable.
             */
            status: string;
            /**
             * Version
             * @description Running application version.
             */
            version: string;
            /**
             * Environment
             * @description Deployment environment (development/staging/production).
             */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             * @description UTC time this response was generated.
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_ticker_prices_tickers__symbol__prices_get: {
        parameters: {
            query: {
                /** @description Bar granularity: '1d', '1w', or '1mo' */
                timeframe?: string;
                /** @description Start date inclusive, YYYY-MM-DD */
                from: string;
                /** @description End date inclusive, YYYY-MM-DD */
                to: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["PriceBarPageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": { detail: string };
                };
            };
            /** @description Validation Error */
            422: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": { detail: unknown };
                };
            };
        };
    };
    search_tickers_tickers_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["TickerSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": { detail: unknown };
                };
            };
        };
    };
    get_ticker_tickers__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["TickerSearchResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": { detail: string };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
