/**
 * This file was auto-generated by openapi-typescript and then manually extended.
 * Run `npm run generate` (with the backend server running) to regenerate from the live spec.
 * Last updated: 2026-06-15 — added /tickers/{symbol}/fundamentals, /dcf, /peers paths.
 */

export interface paths {
  "/tickers/{symbol}/fundamentals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full fundamental analysis: ratios, quality, growth, and 0–100 subscores */
    get: operations["get_fundamentals_tickers__symbol__fundamentals_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickers/{symbol}/dcf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Simplified 2-stage DCF with adjustable assumptions via query params */
    get: operations["get_dcf_tickers__symbol__dcf_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickers/{symbol}/peers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Same-sector peers ranked by market-cap proximity */
    get: operations["get_peers_tickers__symbol__peers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickers/{symbol}/prices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get paginated OHLCV price bars for a ticker */
    get: operations["get_ticker_prices_tickers__symbol__prices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickers/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search tickers by symbol or name prefix */
    get: operations["search_tickers_tickers_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickers/{symbol}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single ticker by symbol */
    get: operations["get_ticker_tickers__symbol__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Returns 200 OK with service metadata.
     */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Single ticker entry returned by search and detail endpoints. */
    TickerSearchResult: {
      symbol: string;
      name: string;
      exchange: string;
      asset_type: string;
      currency: string;
      sector?: string | null;
      industry?: string | null;
      /** ISO 8601 datetime of the most recent price bar, or null if no data yet. */
      data_as_of?: string | null;
    };
    /** A single OHLCV candlestick bar. */
    PriceBarItem: {
      /** ISO 8601 timestamp */
      t: string;
      o: number;
      h: number;
      low: number;
      c: number;
      v: number;
      adj_c?: number | null;
    };
    /** Paginated OHLCV response for a single ticker and timeframe. */
    PriceBarPageResponse: {
      symbol: string;
      timeframe: string;
      data_as_of?: string | null;
      bars: components["schemas"]["PriceBarItem"][];
      next_cursor?: string | null;
    };
    /** Paginated response for the search endpoint. */
    TickerSearchResponse: {
      results: components["schemas"]["TickerSearchResult"][];
      total: number;
    };
    /**
     * HealthResponse
     * @description Shape of the /health response body.
     */
    HealthResponse: {
      status: string;
      version: string;
      environment: string;
      /** @format date-time */
      timestamp: string;
    };
    /** Valuation ratios — all fields are null when the required inputs are unavailable. */
    RatioBlock: {
      pe?: number | null;
      pb?: number | null;
      ps?: number | null;
      ev_ebitda?: number | null;
      dividend_yield?: number | null;
      peg?: number | null;
    };
    /** Profitability, safety, and efficiency metrics. */
    QualityBlock: {
      roe?: number | null;
      roic?: number | null;
      gross_margin?: number | null;
      operating_margin?: number | null;
      net_margin?: number | null;
      debt_to_equity?: number | null;
      interest_coverage?: number | null;
    };
    /** Revenue, EPS, and FCF CAGR metrics. All rates are decimal ratios (e.g. 0.08 = 8 %). */
    GrowthBlock: {
      revenue_cagr_1y?: number | null;
      revenue_cagr_3y?: number | null;
      revenue_cagr_5y?: number | null;
      revenue_years_used_5y?: number | null;
      eps_cagr_1y?: number | null;
      eps_cagr_3y?: number | null;
      eps_cagr_5y?: number | null;
      eps_years_used_5y?: number | null;
      fcf_cagr_1y?: number | null;
      fcf_cagr_3y?: number | null;
      fcf_cagr_5y?: number | null;
      fcf_years_used_5y?: number | null;
    };
    /** Value / Quality / Growth subscores + overall, each 0–100 (null when insufficient data). */
    SubscoreBlock: {
      overall?: number | null;
      value?: number | null;
      quality?: number | null;
      growth?: number | null;
      weights_version: string;
    };
    /** Full fundamental analysis response for a single ticker. */
    FundamentalsResponse: {
      symbol: string;
      /** ISO 8601 date of the snapshot used */
      data_as_of: string;
      ratios: components["schemas"]["RatioBlock"];
      quality: components["schemas"]["QualityBlock"];
      growth: components["schemas"]["GrowthBlock"];
      scores: components["schemas"]["SubscoreBlock"];
    };
    /** Projected and discounted FCF for one year of the DCF model. */
    DcfYearItem: {
      year: number;
      projected_fcf: number;
      discounted_fcf: number;
    };
    /** Simplified 2-stage DCF output. */
    DcfResponse: {
      symbol: string;
      intrinsic_value_per_share?: number | null;
      enterprise_value: number;
      equity_value: number;
      terminal_value: number;
      /** Echoed assumption inputs (growth_rate, discount_rate, terminal_growth, years, base_fcf). */
      assumptions: Record<string, number>;
      yearly_fcf: components["schemas"]["DcfYearItem"][];
    };
    /** Headline data for a single peer ticker. */
    PeerItem: {
      symbol: string;
      name: string;
      market_cap?: number | null;
      pe?: number | null;
      pb?: number | null;
      ps?: number | null;
      ev_ebitda?: number | null;
      dividend_yield?: number | null;
      overall_score?: number | null;
    };
    /** Peer-comparison payload. */
    PeersResponse: {
      symbol: string;
      peers: components["schemas"]["PeerItem"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_fundamentals_tickers__symbol__fundamentals_get: {
    parameters: {
      query?: never;
      header?: never;
      path: { symbol: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["FundamentalsResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  get_dcf_tickers__symbol__dcf_get: {
    parameters: {
      query?: {
        /** @description Near-term FCF growth rate (0–1, default 0.08) */
        growth_rate?: number;
        /** @description WACC / discount rate (0–1, default 0.10) */
        discount_rate?: number;
        /** @description Gordon terminal growth rate — must be < discount_rate */
        terminal_growth?: number;
        /** @description Projection years (1–15, default 5) */
        years?: number;
      };
      header?: never;
      path: { symbol: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["DcfResponse"];
        };
      };
      /** @description Bad Request — terminal_growth >= discount_rate */
      400: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
      /** @description Not Found */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  get_peers_tickers__symbol__peers_get: {
    parameters: {
      query?: {
        /** @description Maximum peers to return (1–10, default 5) */
        limit?: number;
      };
      header?: never;
      path: { symbol: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["PeersResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  get_ticker_prices_tickers__symbol__prices_get: {
    parameters: {
      query: {
        timeframe?: string;
        from: string;
        to: string;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: { symbol: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["PriceBarPageResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
      /** @description Validation Error */
      422: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: unknown };
        };
      };
    };
  };
  search_tickers_tickers_search_get: {
    parameters: {
      query: { q: string; limit?: number };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["TickerSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: unknown };
        };
      };
    };
  };
  get_ticker_tickers__symbol__get: {
    parameters: {
      query?: never;
      header?: never;
      path: { symbol: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["TickerSearchResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
